[workspace]
resolver = "2"
members = [
    "crates/biometrics-common",
    "crates/hardware-common",
    "crates/keymaster",
    "crates/nativewindow",
    "crates/face",
    "crates/service",
]

[workspace.dependencies]
binder = { package = "android-binder", path = "third_party/binder" }

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
panic = "abort"
strip = "symbols"
